### PR TITLE
Separate dependencies from Bodega

### PR DESCRIPTION
**Pull request by dannynorth**
PR #20 essentially asks for the ability to use Bodega without using any dependencies. This PR provides a possible implementation for that.

The main idea is that Bodega now exposes two possible libraries to use:

1. BodegaCore - the bulk of the existing functionality, but without the SQLiteStorageEngine
2. Bodega - the existing SQliteStorageEngine implementation

For everyone who wants the simple use-case, they can continue to `import Bodega`. The Bodega target does an `@_exported import BodegaCore`, which means that it re-exposes all the types and symbols of BodegaCore, as if they came from Bodega itself.

For the occasional user who wants to use Bodega *without* dependencies, they would `import BodegaCore` and then implement their own StorageEngine themselves in their own code (such as one that uses the system SQLite3 module as the basis for storage).

The code changes to support this are very minimal:
1. The addition of a new target + product in Package.swift
2. Moving the bulk of the files to a new BodegaCore folder
3. Changing `CacheKey.rawValue` to be public so it can be accessed by the SQLiteStorageEngine
4. Adding a testable import of BodegaCore in a unit test file

### CODE REVIEW

**Comment by dannynorth** [comment]
@brettohland I'd be interested to get your thoughts on this. Would this approach work for your case? I think you would still see SQLite.swift show up in the list of dependencies, but it wouldn't actually get *linked* into your app if you only did `import BodegaCore`.

**Comment by mergesort** [comment]
Thank you so much @dannynorth! I was just looking at @brettohland's pull request this week and brainstorming a way to accommodate their needs without necessarily dropping SQLite.swift entirely since I don't feel comfortable with writing raw SQLite. I'll likely merge this in regardless, but I'd love to find out if this provides a nice middle ground for Brett.

**Comment by brettohland** [comment]
> @brettohland I'd be interested to get your thoughts on this. Would this approach work for your case? I think you would still see SQLite.swift show up in the list of dependencies, but it wouldn't actually get _linked_ into your app if you only did `import BodegaCore`.

@dannynorth At the end of the day, it's Boutique that I've integrated into my project which is where I'm needing to reduce my external dependencies. If there were some sort of modular set of dependencies there that would integrate this then that would be ideal.

 > Thank you so much @dannynorth! I was just looking at @brettohland's pull request this week and brainstorming a way to accommodate their needs without necessarily dropping SQLite.swift entirely since I don't feel comfortable with writing raw SQLite. I'll likely merge this in regardless, but I'd love to find out if this provides a nice middle ground for Brett.

@mergesort I can absolutely appreciate the balancing act that's needed here, my needs are definitely uncommon. There absolutely needs to be some built-in storage engines ready to go for use in Boutique to make integration simple.

I do understand the hesitancy of dropping SQLite.swift, which is well tested and proven, to roll your own code to interact with the C API. I've been dog-fooding the C-based SQLite storage engine from my PR in my current project since I pushed it up in March and it's been working really well. No real performance issues, and the app has at least 10 stores in use at any time. But who knows if I'm hitting all of the possible performance issues my code might introduce.

I wonder if the idea here of having a `Core` module could be extended to Boutique as well? `BoutiqueCore` could import `BodegaCore` and essentially force the user to roll their own storage engines.

**Comment by mergesort** [comment]
Hey @brettohland, sorry once again for the delayed reply. I've been thinking about how the balance between maintainability (such as using SQLite.swift vs. rolling my own SQLite code), and how many people would be impacted, and I think my final decision is unfortunately to side with ease of maintenance.

The approach you suggested to split Boutique and Bodega into Core modules is definitely doable, but I think by adding all of these independent interactable layers some of the simplicity of Boutique gets lost. While I aim to support as many use cases as I can, I'm also considering the additional complexity involved in managing the project and the changes don't sit well with me. That's a personal decision, you and others may feel another way and I completely understand. It's not one rooted in numbers or facts I can use to justify the decision, but more in how it would make me feel to maintain Boutique.

Hope that's not too disappointing, and I do appreciate all the time, energy, and effort you've put into thinking about and exploring this route. If I change my mind I promise I'll let you know.

**Pull request closed without merging**
